version: "3.7"

services:
  web:
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    restart: always
    ports:
     - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes: ['./api:/api']

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
