"""empty message

Revision ID: c42aef390d35
Revises: 267dff1d4495
Create Date: 2023-02-03 04:03:05.148418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c42aef390d35"
down_revision = "267dff1d4495"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "association_table",
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("weather_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city.id"],
        ),
        sa.ForeignKeyConstraint(
            ["weather_id"],
            ["weather.id"],
        ),
        sa.PrimaryKeyConstraint("city_id", "weather_id"),
    )
    op.drop_constraint("city_weather_id_fkey", "city", type_="foreignkey")
    op.drop_column("city", "weather_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "city",
        sa.Column("weather_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "city_weather_id_fkey", "city", "weather", ["weather_id"], ["id"]
    )
    op.drop_table("association_table")
    # ### end Alembic commands ###
