"""empty message

Revision ID: 6df349b629ab
Revises: c42aef390d35
Create Date: 2023-02-03 04:07:27.779143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6df349b629ab"
down_revision = "c42aef390d35"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weather",
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("weather", "time_created")
    # ### end Alembic commands ###
