"""empty message

Revision ID: 4e6afe947aed
Revises: 6df349b629ab
Create Date: 2023-02-03 04:12:29.514330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e6afe947aed"
down_revision = "6df349b629ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city_weather_table",
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("weather_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city.id"],
        ),
        sa.ForeignKeyConstraint(
            ["weather_id"],
            ["weather.id"],
        ),
        sa.PrimaryKeyConstraint("city_id", "weather_id"),
    )
    op.drop_table("association_table")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "association_table",
        sa.Column("city_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("weather_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"], ["city.id"], name="association_table_city_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["weather_id"], ["weather.id"], name="association_table_weather_id_fkey"
        ),
        sa.PrimaryKeyConstraint("city_id", "weather_id", name="association_table_pkey"),
    )
    op.drop_table("city_weather_table")
    # ### end Alembic commands ###
