"""empty message

Revision ID: 6d83d01c07dd
Revises: 
Create Date: 2023-02-02 18:33:03.075749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d83d01c07dd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("temperatures", sa.Integer(), nullable=False),
        sa.Column("atmospheric_pressure", sa.Integer(), nullable=False),
        sa.Column("wind_speed", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weather_id"), "weather", ["id"], unique=False)
    op.create_table(
        "city",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("weather_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["weather_id"],
            ["weather.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_city_id"), "city", ["id"], unique=False)
    op.create_index(op.f("ix_city_name"), "city", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_city_name"), table_name="city")
    op.drop_index(op.f("ix_city_id"), table_name="city")
    op.drop_table("city")
    op.drop_index(op.f("ix_weather_id"), table_name="weather")
    op.drop_table("weather")
    # ### end Alembic commands ###
